// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"context"
	"github.com/kernel/hypeman/cmd/api/api"
	"github.com/kernel/hypeman/cmd/api/config"
	"github.com/kernel/hypeman/lib/builds"
	"github.com/kernel/hypeman/lib/devices"
	"github.com/kernel/hypeman/lib/images"
	"github.com/kernel/hypeman/lib/ingress"
	"github.com/kernel/hypeman/lib/instances"
	"github.com/kernel/hypeman/lib/network"
	"github.com/kernel/hypeman/lib/providers"
	"github.com/kernel/hypeman/lib/registry"
	"github.com/kernel/hypeman/lib/resources"
	"github.com/kernel/hypeman/lib/system"
	"github.com/kernel/hypeman/lib/volumes"
	"log/slog"
)

import (
	_ "embed"
)

// Injectors from wire.go:

// initializeApp is the injector function
func initializeApp() (*application, func(), error) {
	config := providers.ProvideConfig()
	paths := providers.ProvidePaths(config)
	logger := providers.ProvideLogger(paths)
	context := providers.ProvideContext(logger)
	manager, err := providers.ProvideImageManager(paths, config)
	if err != nil {
		return nil, nil, err
	}
	systemManager := providers.ProvideSystemManager(paths)
	networkManager := providers.ProvideNetworkManager(paths, config)
	devicesManager := providers.ProvideDeviceManager(paths)
	volumesManager, err := providers.ProvideVolumeManager(paths, config)
	if err != nil {
		return nil, nil, err
	}
	instancesManager, err := providers.ProvideInstanceManager(paths, config, manager, systemManager, networkManager, devicesManager, volumesManager)
	if err != nil {
		return nil, nil, err
	}
	ingressManager, err := providers.ProvideIngressManager(paths, config, instancesManager)
	if err != nil {
		return nil, nil, err
	}
	buildsManager, err := providers.ProvideBuildManager(paths, config, instancesManager, volumesManager, manager, logger)
	if err != nil {
		return nil, nil, err
	}
	resourcesManager, err := providers.ProvideResourceManager(context, config, paths, manager, instancesManager, volumesManager)
	if err != nil {
		return nil, nil, err
	}
	registry, err := providers.ProvideRegistry(paths, manager)
	if err != nil {
		return nil, nil, err
	}
	apiService := api.New(config, manager, instancesManager, volumesManager, networkManager, devicesManager, ingressManager, buildsManager, resourcesManager)
	mainApplication := &application{
		Ctx:             context,
		Logger:          logger,
		Config:          config,
		ImageManager:    manager,
		SystemManager:   systemManager,
		NetworkManager:  networkManager,
		DeviceManager:   devicesManager,
		InstanceManager: instancesManager,
		VolumeManager:   volumesManager,
		IngressManager:  ingressManager,
		BuildManager:    buildsManager,
		ResourceManager: resourcesManager,
		Registry:        registry,
		ApiService:      apiService,
	}
	return mainApplication, func() {
	}, nil
}

// wire.go:

// application struct to hold initialized components
type application struct {
	Ctx             context.Context
	Logger          *slog.Logger
	Config          *config.Config
	ImageManager    images.Manager
	SystemManager   system.Manager
	NetworkManager  network.Manager
	DeviceManager   devices.Manager
	InstanceManager instances.Manager
	VolumeManager   volumes.Manager
	IngressManager  ingress.Manager
	BuildManager    builds.Manager
	ResourceManager *resources.Manager
	Registry        *registry.Registry
	ApiService      *api.ApiService
}
