// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.12
// source: lib/guest/guest.proto

package guest

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ExecRequest represents messages from client to server
type ExecRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Request:
	//
	//	*ExecRequest_Start
	//	*ExecRequest_Stdin
	//	*ExecRequest_Resize
	Request       isExecRequest_Request `protobuf_oneof:"request"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecRequest) Reset() {
	*x = ExecRequest{}
	mi := &file_lib_guest_guest_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecRequest) ProtoMessage() {}

func (x *ExecRequest) ProtoReflect() protoreflect.Message {
	mi := &file_lib_guest_guest_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecRequest.ProtoReflect.Descriptor instead.
func (*ExecRequest) Descriptor() ([]byte, []int) {
	return file_lib_guest_guest_proto_rawDescGZIP(), []int{0}
}

func (x *ExecRequest) GetRequest() isExecRequest_Request {
	if x != nil {
		return x.Request
	}
	return nil
}

func (x *ExecRequest) GetStart() *ExecStart {
	if x != nil {
		if x, ok := x.Request.(*ExecRequest_Start); ok {
			return x.Start
		}
	}
	return nil
}

func (x *ExecRequest) GetStdin() []byte {
	if x != nil {
		if x, ok := x.Request.(*ExecRequest_Stdin); ok {
			return x.Stdin
		}
	}
	return nil
}

func (x *ExecRequest) GetResize() *WindowSize {
	if x != nil {
		if x, ok := x.Request.(*ExecRequest_Resize); ok {
			return x.Resize
		}
	}
	return nil
}

type isExecRequest_Request interface {
	isExecRequest_Request()
}

type ExecRequest_Start struct {
	Start *ExecStart `protobuf:"bytes,1,opt,name=start,proto3,oneof"` // Initial exec request
}

type ExecRequest_Stdin struct {
	Stdin []byte `protobuf:"bytes,2,opt,name=stdin,proto3,oneof"` // Stdin data
}

type ExecRequest_Resize struct {
	Resize *WindowSize `protobuf:"bytes,3,opt,name=resize,proto3,oneof"` // Window resize event
}

func (*ExecRequest_Start) isExecRequest_Request() {}

func (*ExecRequest_Stdin) isExecRequest_Request() {}

func (*ExecRequest_Resize) isExecRequest_Request() {}

// ExecStart initiates command execution
type ExecStart struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Command        []string               `protobuf:"bytes,1,rep,name=command,proto3" json:"command,omitempty"`                                                                   // Command and arguments
	Tty            bool                   `protobuf:"varint,2,opt,name=tty,proto3" json:"tty,omitempty"`                                                                          // Allocate pseudo-TTY
	Env            map[string]string      `protobuf:"bytes,3,rep,name=env,proto3" json:"env,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // Environment variables
	Cwd            string                 `protobuf:"bytes,4,opt,name=cwd,proto3" json:"cwd,omitempty"`                                                                           // Working directory (optional)
	TimeoutSeconds int32                  `protobuf:"varint,5,opt,name=timeout_seconds,json=timeoutSeconds,proto3" json:"timeout_seconds,omitempty"`                              // Execution timeout in seconds (0 = no timeout)
	Rows           uint32                 `protobuf:"varint,6,opt,name=rows,proto3" json:"rows,omitempty"`                                                                        // Initial terminal rows (0 = default 24)
	Cols           uint32                 `protobuf:"varint,7,opt,name=cols,proto3" json:"cols,omitempty"`                                                                        // Initial terminal cols (0 = default 80)
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ExecStart) Reset() {
	*x = ExecStart{}
	mi := &file_lib_guest_guest_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecStart) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecStart) ProtoMessage() {}

func (x *ExecStart) ProtoReflect() protoreflect.Message {
	mi := &file_lib_guest_guest_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecStart.ProtoReflect.Descriptor instead.
func (*ExecStart) Descriptor() ([]byte, []int) {
	return file_lib_guest_guest_proto_rawDescGZIP(), []int{1}
}

func (x *ExecStart) GetCommand() []string {
	if x != nil {
		return x.Command
	}
	return nil
}

func (x *ExecStart) GetTty() bool {
	if x != nil {
		return x.Tty
	}
	return false
}

func (x *ExecStart) GetEnv() map[string]string {
	if x != nil {
		return x.Env
	}
	return nil
}

func (x *ExecStart) GetCwd() string {
	if x != nil {
		return x.Cwd
	}
	return ""
}

func (x *ExecStart) GetTimeoutSeconds() int32 {
	if x != nil {
		return x.TimeoutSeconds
	}
	return 0
}

func (x *ExecStart) GetRows() uint32 {
	if x != nil {
		return x.Rows
	}
	return 0
}

func (x *ExecStart) GetCols() uint32 {
	if x != nil {
		return x.Cols
	}
	return 0
}

// WindowSize represents terminal window dimensions for resize events
type WindowSize struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Rows          uint32                 `protobuf:"varint,1,opt,name=rows,proto3" json:"rows,omitempty"`
	Cols          uint32                 `protobuf:"varint,2,opt,name=cols,proto3" json:"cols,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WindowSize) Reset() {
	*x = WindowSize{}
	mi := &file_lib_guest_guest_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WindowSize) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WindowSize) ProtoMessage() {}

func (x *WindowSize) ProtoReflect() protoreflect.Message {
	mi := &file_lib_guest_guest_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WindowSize.ProtoReflect.Descriptor instead.
func (*WindowSize) Descriptor() ([]byte, []int) {
	return file_lib_guest_guest_proto_rawDescGZIP(), []int{2}
}

func (x *WindowSize) GetRows() uint32 {
	if x != nil {
		return x.Rows
	}
	return 0
}

func (x *WindowSize) GetCols() uint32 {
	if x != nil {
		return x.Cols
	}
	return 0
}

// ExecResponse represents messages from server to client
type ExecResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Response:
	//
	//	*ExecResponse_Stdout
	//	*ExecResponse_Stderr
	//	*ExecResponse_ExitCode
	Response      isExecResponse_Response `protobuf_oneof:"response"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecResponse) Reset() {
	*x = ExecResponse{}
	mi := &file_lib_guest_guest_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecResponse) ProtoMessage() {}

func (x *ExecResponse) ProtoReflect() protoreflect.Message {
	mi := &file_lib_guest_guest_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecResponse.ProtoReflect.Descriptor instead.
func (*ExecResponse) Descriptor() ([]byte, []int) {
	return file_lib_guest_guest_proto_rawDescGZIP(), []int{3}
}

func (x *ExecResponse) GetResponse() isExecResponse_Response {
	if x != nil {
		return x.Response
	}
	return nil
}

func (x *ExecResponse) GetStdout() []byte {
	if x != nil {
		if x, ok := x.Response.(*ExecResponse_Stdout); ok {
			return x.Stdout
		}
	}
	return nil
}

func (x *ExecResponse) GetStderr() []byte {
	if x != nil {
		if x, ok := x.Response.(*ExecResponse_Stderr); ok {
			return x.Stderr
		}
	}
	return nil
}

func (x *ExecResponse) GetExitCode() int32 {
	if x != nil {
		if x, ok := x.Response.(*ExecResponse_ExitCode); ok {
			return x.ExitCode
		}
	}
	return 0
}

type isExecResponse_Response interface {
	isExecResponse_Response()
}

type ExecResponse_Stdout struct {
	Stdout []byte `protobuf:"bytes,1,opt,name=stdout,proto3,oneof"` // Stdout data
}

type ExecResponse_Stderr struct {
	Stderr []byte `protobuf:"bytes,2,opt,name=stderr,proto3,oneof"` // Stderr data
}

type ExecResponse_ExitCode struct {
	ExitCode int32 `protobuf:"varint,3,opt,name=exit_code,json=exitCode,proto3,oneof"` // Command exit code (final message)
}

func (*ExecResponse_Stdout) isExecResponse_Response() {}

func (*ExecResponse_Stderr) isExecResponse_Response() {}

func (*ExecResponse_ExitCode) isExecResponse_Response() {}

// CopyToGuestRequest represents messages for copying files to guest
type CopyToGuestRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Request:
	//
	//	*CopyToGuestRequest_Start
	//	*CopyToGuestRequest_Data
	//	*CopyToGuestRequest_End
	Request       isCopyToGuestRequest_Request `protobuf_oneof:"request"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CopyToGuestRequest) Reset() {
	*x = CopyToGuestRequest{}
	mi := &file_lib_guest_guest_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CopyToGuestRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CopyToGuestRequest) ProtoMessage() {}

func (x *CopyToGuestRequest) ProtoReflect() protoreflect.Message {
	mi := &file_lib_guest_guest_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CopyToGuestRequest.ProtoReflect.Descriptor instead.
func (*CopyToGuestRequest) Descriptor() ([]byte, []int) {
	return file_lib_guest_guest_proto_rawDescGZIP(), []int{4}
}

func (x *CopyToGuestRequest) GetRequest() isCopyToGuestRequest_Request {
	if x != nil {
		return x.Request
	}
	return nil
}

func (x *CopyToGuestRequest) GetStart() *CopyToGuestStart {
	if x != nil {
		if x, ok := x.Request.(*CopyToGuestRequest_Start); ok {
			return x.Start
		}
	}
	return nil
}

func (x *CopyToGuestRequest) GetData() []byte {
	if x != nil {
		if x, ok := x.Request.(*CopyToGuestRequest_Data); ok {
			return x.Data
		}
	}
	return nil
}

func (x *CopyToGuestRequest) GetEnd() *CopyToGuestEnd {
	if x != nil {
		if x, ok := x.Request.(*CopyToGuestRequest_End); ok {
			return x.End
		}
	}
	return nil
}

type isCopyToGuestRequest_Request interface {
	isCopyToGuestRequest_Request()
}

type CopyToGuestRequest_Start struct {
	Start *CopyToGuestStart `protobuf:"bytes,1,opt,name=start,proto3,oneof"` // Initial copy request with metadata
}

type CopyToGuestRequest_Data struct {
	Data []byte `protobuf:"bytes,2,opt,name=data,proto3,oneof"` // File content chunk
}

type CopyToGuestRequest_End struct {
	End *CopyToGuestEnd `protobuf:"bytes,3,opt,name=end,proto3,oneof"` // End of file marker
}

func (*CopyToGuestRequest_Start) isCopyToGuestRequest_Request() {}

func (*CopyToGuestRequest_Data) isCopyToGuestRequest_Request() {}

func (*CopyToGuestRequest_End) isCopyToGuestRequest_Request() {}

// CopyToGuestStart initiates a copy-to-guest operation
type CopyToGuestStart struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`                 // Destination path in guest
	Mode          uint32                 `protobuf:"varint,2,opt,name=mode,proto3" json:"mode,omitempty"`                // File mode (permissions)
	IsDir         bool                   `protobuf:"varint,3,opt,name=is_dir,json=isDir,proto3" json:"is_dir,omitempty"` // True if this is a directory
	Size          int64                  `protobuf:"varint,4,opt,name=size,proto3" json:"size,omitempty"`                // Expected total size (0 for directories)
	Mtime         int64                  `protobuf:"varint,5,opt,name=mtime,proto3" json:"mtime,omitempty"`              // Modification time (Unix timestamp)
	Uid           uint32                 `protobuf:"varint,6,opt,name=uid,proto3" json:"uid,omitempty"`                  // User ID (archive mode only, 0 = use default)
	Gid           uint32                 `protobuf:"varint,7,opt,name=gid,proto3" json:"gid,omitempty"`                  // Group ID (archive mode only, 0 = use default)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CopyToGuestStart) Reset() {
	*x = CopyToGuestStart{}
	mi := &file_lib_guest_guest_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CopyToGuestStart) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CopyToGuestStart) ProtoMessage() {}

func (x *CopyToGuestStart) ProtoReflect() protoreflect.Message {
	mi := &file_lib_guest_guest_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CopyToGuestStart.ProtoReflect.Descriptor instead.
func (*CopyToGuestStart) Descriptor() ([]byte, []int) {
	return file_lib_guest_guest_proto_rawDescGZIP(), []int{5}
}

func (x *CopyToGuestStart) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *CopyToGuestStart) GetMode() uint32 {
	if x != nil {
		return x.Mode
	}
	return 0
}

func (x *CopyToGuestStart) GetIsDir() bool {
	if x != nil {
		return x.IsDir
	}
	return false
}

func (x *CopyToGuestStart) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *CopyToGuestStart) GetMtime() int64 {
	if x != nil {
		return x.Mtime
	}
	return 0
}

func (x *CopyToGuestStart) GetUid() uint32 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *CopyToGuestStart) GetGid() uint32 {
	if x != nil {
		return x.Gid
	}
	return 0
}

// CopyToGuestEnd signals the end of a file transfer
type CopyToGuestEnd struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CopyToGuestEnd) Reset() {
	*x = CopyToGuestEnd{}
	mi := &file_lib_guest_guest_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CopyToGuestEnd) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CopyToGuestEnd) ProtoMessage() {}

func (x *CopyToGuestEnd) ProtoReflect() protoreflect.Message {
	mi := &file_lib_guest_guest_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CopyToGuestEnd.ProtoReflect.Descriptor instead.
func (*CopyToGuestEnd) Descriptor() ([]byte, []int) {
	return file_lib_guest_guest_proto_rawDescGZIP(), []int{6}
}

// CopyToGuestResponse is the response after a copy-to-guest operation
type CopyToGuestResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`                               // Whether the copy succeeded
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`                                    // Error message if failed
	BytesWritten  int64                  `protobuf:"varint,3,opt,name=bytes_written,json=bytesWritten,proto3" json:"bytes_written,omitempty"` // Total bytes written
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CopyToGuestResponse) Reset() {
	*x = CopyToGuestResponse{}
	mi := &file_lib_guest_guest_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CopyToGuestResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CopyToGuestResponse) ProtoMessage() {}

func (x *CopyToGuestResponse) ProtoReflect() protoreflect.Message {
	mi := &file_lib_guest_guest_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CopyToGuestResponse.ProtoReflect.Descriptor instead.
func (*CopyToGuestResponse) Descriptor() ([]byte, []int) {
	return file_lib_guest_guest_proto_rawDescGZIP(), []int{7}
}

func (x *CopyToGuestResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *CopyToGuestResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *CopyToGuestResponse) GetBytesWritten() int64 {
	if x != nil {
		return x.BytesWritten
	}
	return 0
}

// CopyFromGuestRequest initiates a copy-from-guest operation
type CopyFromGuestRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`                                   // Source path in guest
	FollowLinks   bool                   `protobuf:"varint,2,opt,name=follow_links,json=followLinks,proto3" json:"follow_links,omitempty"` // Follow symbolic links (like -L flag)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CopyFromGuestRequest) Reset() {
	*x = CopyFromGuestRequest{}
	mi := &file_lib_guest_guest_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CopyFromGuestRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CopyFromGuestRequest) ProtoMessage() {}

func (x *CopyFromGuestRequest) ProtoReflect() protoreflect.Message {
	mi := &file_lib_guest_guest_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CopyFromGuestRequest.ProtoReflect.Descriptor instead.
func (*CopyFromGuestRequest) Descriptor() ([]byte, []int) {
	return file_lib_guest_guest_proto_rawDescGZIP(), []int{8}
}

func (x *CopyFromGuestRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *CopyFromGuestRequest) GetFollowLinks() bool {
	if x != nil {
		return x.FollowLinks
	}
	return false
}

// CopyFromGuestResponse streams file data from guest
type CopyFromGuestResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Response:
	//
	//	*CopyFromGuestResponse_Header
	//	*CopyFromGuestResponse_Data
	//	*CopyFromGuestResponse_End
	//	*CopyFromGuestResponse_Error
	Response      isCopyFromGuestResponse_Response `protobuf_oneof:"response"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CopyFromGuestResponse) Reset() {
	*x = CopyFromGuestResponse{}
	mi := &file_lib_guest_guest_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CopyFromGuestResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CopyFromGuestResponse) ProtoMessage() {}

func (x *CopyFromGuestResponse) ProtoReflect() protoreflect.Message {
	mi := &file_lib_guest_guest_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CopyFromGuestResponse.ProtoReflect.Descriptor instead.
func (*CopyFromGuestResponse) Descriptor() ([]byte, []int) {
	return file_lib_guest_guest_proto_rawDescGZIP(), []int{9}
}

func (x *CopyFromGuestResponse) GetResponse() isCopyFromGuestResponse_Response {
	if x != nil {
		return x.Response
	}
	return nil
}

func (x *CopyFromGuestResponse) GetHeader() *CopyFromGuestHeader {
	if x != nil {
		if x, ok := x.Response.(*CopyFromGuestResponse_Header); ok {
			return x.Header
		}
	}
	return nil
}

func (x *CopyFromGuestResponse) GetData() []byte {
	if x != nil {
		if x, ok := x.Response.(*CopyFromGuestResponse_Data); ok {
			return x.Data
		}
	}
	return nil
}

func (x *CopyFromGuestResponse) GetEnd() *CopyFromGuestEnd {
	if x != nil {
		if x, ok := x.Response.(*CopyFromGuestResponse_End); ok {
			return x.End
		}
	}
	return nil
}

func (x *CopyFromGuestResponse) GetError() *CopyFromGuestError {
	if x != nil {
		if x, ok := x.Response.(*CopyFromGuestResponse_Error); ok {
			return x.Error
		}
	}
	return nil
}

type isCopyFromGuestResponse_Response interface {
	isCopyFromGuestResponse_Response()
}

type CopyFromGuestResponse_Header struct {
	Header *CopyFromGuestHeader `protobuf:"bytes,1,opt,name=header,proto3,oneof"` // File/directory metadata
}

type CopyFromGuestResponse_Data struct {
	Data []byte `protobuf:"bytes,2,opt,name=data,proto3,oneof"` // File content chunk
}

type CopyFromGuestResponse_End struct {
	End *CopyFromGuestEnd `protobuf:"bytes,3,opt,name=end,proto3,oneof"` // End of file/transfer marker
}

type CopyFromGuestResponse_Error struct {
	Error *CopyFromGuestError `protobuf:"bytes,4,opt,name=error,proto3,oneof"` // Error during copy
}

func (*CopyFromGuestResponse_Header) isCopyFromGuestResponse_Response() {}

func (*CopyFromGuestResponse_Data) isCopyFromGuestResponse_Response() {}

func (*CopyFromGuestResponse_End) isCopyFromGuestResponse_Response() {}

func (*CopyFromGuestResponse_Error) isCopyFromGuestResponse_Response() {}

// CopyFromGuestHeader provides metadata about a file being copied
type CopyFromGuestHeader struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`                               // Relative path from copy root
	Mode          uint32                 `protobuf:"varint,2,opt,name=mode,proto3" json:"mode,omitempty"`                              // File mode (permissions)
	IsDir         bool                   `protobuf:"varint,3,opt,name=is_dir,json=isDir,proto3" json:"is_dir,omitempty"`               // True if this is a directory
	IsSymlink     bool                   `protobuf:"varint,4,opt,name=is_symlink,json=isSymlink,proto3" json:"is_symlink,omitempty"`   // True if this is a symbolic link
	LinkTarget    string                 `protobuf:"bytes,5,opt,name=link_target,json=linkTarget,proto3" json:"link_target,omitempty"` // Symlink target (if is_symlink)
	Size          int64                  `protobuf:"varint,6,opt,name=size,proto3" json:"size,omitempty"`                              // File size (0 for directories)
	Mtime         int64                  `protobuf:"varint,7,opt,name=mtime,proto3" json:"mtime,omitempty"`                            // Modification time (Unix timestamp)
	Uid           uint32                 `protobuf:"varint,8,opt,name=uid,proto3" json:"uid,omitempty"`                                // User ID
	Gid           uint32                 `protobuf:"varint,9,opt,name=gid,proto3" json:"gid,omitempty"`                                // Group ID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CopyFromGuestHeader) Reset() {
	*x = CopyFromGuestHeader{}
	mi := &file_lib_guest_guest_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CopyFromGuestHeader) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CopyFromGuestHeader) ProtoMessage() {}

func (x *CopyFromGuestHeader) ProtoReflect() protoreflect.Message {
	mi := &file_lib_guest_guest_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CopyFromGuestHeader.ProtoReflect.Descriptor instead.
func (*CopyFromGuestHeader) Descriptor() ([]byte, []int) {
	return file_lib_guest_guest_proto_rawDescGZIP(), []int{10}
}

func (x *CopyFromGuestHeader) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *CopyFromGuestHeader) GetMode() uint32 {
	if x != nil {
		return x.Mode
	}
	return 0
}

func (x *CopyFromGuestHeader) GetIsDir() bool {
	if x != nil {
		return x.IsDir
	}
	return false
}

func (x *CopyFromGuestHeader) GetIsSymlink() bool {
	if x != nil {
		return x.IsSymlink
	}
	return false
}

func (x *CopyFromGuestHeader) GetLinkTarget() string {
	if x != nil {
		return x.LinkTarget
	}
	return ""
}

func (x *CopyFromGuestHeader) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *CopyFromGuestHeader) GetMtime() int64 {
	if x != nil {
		return x.Mtime
	}
	return 0
}

func (x *CopyFromGuestHeader) GetUid() uint32 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *CopyFromGuestHeader) GetGid() uint32 {
	if x != nil {
		return x.Gid
	}
	return 0
}

// CopyFromGuestEnd signals the end of a file or transfer
type CopyFromGuestEnd struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Final         bool                   `protobuf:"varint,1,opt,name=final,proto3" json:"final,omitempty"` // True if this is the final file
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CopyFromGuestEnd) Reset() {
	*x = CopyFromGuestEnd{}
	mi := &file_lib_guest_guest_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CopyFromGuestEnd) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CopyFromGuestEnd) ProtoMessage() {}

func (x *CopyFromGuestEnd) ProtoReflect() protoreflect.Message {
	mi := &file_lib_guest_guest_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CopyFromGuestEnd.ProtoReflect.Descriptor instead.
func (*CopyFromGuestEnd) Descriptor() ([]byte, []int) {
	return file_lib_guest_guest_proto_rawDescGZIP(), []int{11}
}

func (x *CopyFromGuestEnd) GetFinal() bool {
	if x != nil {
		return x.Final
	}
	return false
}

// CopyFromGuestError reports an error during copy
type CopyFromGuestError struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"` // Error message
	Path          string                 `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`       // Path that caused error (if applicable)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CopyFromGuestError) Reset() {
	*x = CopyFromGuestError{}
	mi := &file_lib_guest_guest_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CopyFromGuestError) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CopyFromGuestError) ProtoMessage() {}

func (x *CopyFromGuestError) ProtoReflect() protoreflect.Message {
	mi := &file_lib_guest_guest_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CopyFromGuestError.ProtoReflect.Descriptor instead.
func (*CopyFromGuestError) Descriptor() ([]byte, []int) {
	return file_lib_guest_guest_proto_rawDescGZIP(), []int{12}
}

func (x *CopyFromGuestError) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *CopyFromGuestError) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

// StatPathRequest requests information about a path
type StatPathRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`                                   // Path to stat
	FollowLinks   bool                   `protobuf:"varint,2,opt,name=follow_links,json=followLinks,proto3" json:"follow_links,omitempty"` // Follow symbolic links
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatPathRequest) Reset() {
	*x = StatPathRequest{}
	mi := &file_lib_guest_guest_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatPathRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatPathRequest) ProtoMessage() {}

func (x *StatPathRequest) ProtoReflect() protoreflect.Message {
	mi := &file_lib_guest_guest_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatPathRequest.ProtoReflect.Descriptor instead.
func (*StatPathRequest) Descriptor() ([]byte, []int) {
	return file_lib_guest_guest_proto_rawDescGZIP(), []int{13}
}

func (x *StatPathRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *StatPathRequest) GetFollowLinks() bool {
	if x != nil {
		return x.FollowLinks
	}
	return false
}

// StatPathResponse contains information about a path
type StatPathResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Exists        bool                   `protobuf:"varint,1,opt,name=exists,proto3" json:"exists,omitempty"`                          // Whether the path exists
	IsDir         bool                   `protobuf:"varint,2,opt,name=is_dir,json=isDir,proto3" json:"is_dir,omitempty"`               // True if this is a directory
	IsFile        bool                   `protobuf:"varint,3,opt,name=is_file,json=isFile,proto3" json:"is_file,omitempty"`            // True if this is a regular file
	IsSymlink     bool                   `protobuf:"varint,4,opt,name=is_symlink,json=isSymlink,proto3" json:"is_symlink,omitempty"`   // True if this is a symbolic link (only if follow_links=false)
	LinkTarget    string                 `protobuf:"bytes,5,opt,name=link_target,json=linkTarget,proto3" json:"link_target,omitempty"` // Symlink target (if is_symlink)
	Mode          uint32                 `protobuf:"varint,6,opt,name=mode,proto3" json:"mode,omitempty"`                              // File mode (permissions)
	Size          int64                  `protobuf:"varint,7,opt,name=size,proto3" json:"size,omitempty"`                              // File size
	Error         string                 `protobuf:"bytes,8,opt,name=error,proto3" json:"error,omitempty"`                             // Error message if stat failed (e.g., permission denied)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatPathResponse) Reset() {
	*x = StatPathResponse{}
	mi := &file_lib_guest_guest_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatPathResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatPathResponse) ProtoMessage() {}

func (x *StatPathResponse) ProtoReflect() protoreflect.Message {
	mi := &file_lib_guest_guest_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatPathResponse.ProtoReflect.Descriptor instead.
func (*StatPathResponse) Descriptor() ([]byte, []int) {
	return file_lib_guest_guest_proto_rawDescGZIP(), []int{14}
}

func (x *StatPathResponse) GetExists() bool {
	if x != nil {
		return x.Exists
	}
	return false
}

func (x *StatPathResponse) GetIsDir() bool {
	if x != nil {
		return x.IsDir
	}
	return false
}

func (x *StatPathResponse) GetIsFile() bool {
	if x != nil {
		return x.IsFile
	}
	return false
}

func (x *StatPathResponse) GetIsSymlink() bool {
	if x != nil {
		return x.IsSymlink
	}
	return false
}

func (x *StatPathResponse) GetLinkTarget() string {
	if x != nil {
		return x.LinkTarget
	}
	return ""
}

func (x *StatPathResponse) GetMode() uint32 {
	if x != nil {
		return x.Mode
	}
	return 0
}

func (x *StatPathResponse) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *StatPathResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

var File_lib_guest_guest_proto protoreflect.FileDescriptor

const file_lib_guest_guest_proto_rawDesc = "" +
	"\n" +
	"\x15lib/guest/guest.proto\x12\x05guest\"\x87\x01\n" +
	"\vExecRequest\x12(\n" +
	"\x05start\x18\x01 \x01(\v2\x10.guest.ExecStartH\x00R\x05start\x12\x16\n" +
	"\x05stdin\x18\x02 \x01(\fH\x00R\x05stdin\x12+\n" +
	"\x06resize\x18\x03 \x01(\v2\x11.guest.WindowSizeH\x00R\x06resizeB\t\n" +
	"\arequest\"\xff\x01\n" +
	"\tExecStart\x12\x18\n" +
	"\acommand\x18\x01 \x03(\tR\acommand\x12\x10\n" +
	"\x03tty\x18\x02 \x01(\bR\x03tty\x12+\n" +
	"\x03env\x18\x03 \x03(\v2\x19.guest.ExecStart.EnvEntryR\x03env\x12\x10\n" +
	"\x03cwd\x18\x04 \x01(\tR\x03cwd\x12'\n" +
	"\x0ftimeout_seconds\x18\x05 \x01(\x05R\x0etimeoutSeconds\x12\x12\n" +
	"\x04rows\x18\x06 \x01(\rR\x04rows\x12\x12\n" +
	"\x04cols\x18\a \x01(\rR\x04cols\x1a6\n" +
	"\bEnvEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"4\n" +
	"\n" +
	"WindowSize\x12\x12\n" +
	"\x04rows\x18\x01 \x01(\rR\x04rows\x12\x12\n" +
	"\x04cols\x18\x02 \x01(\rR\x04cols\"m\n" +
	"\fExecResponse\x12\x18\n" +
	"\x06stdout\x18\x01 \x01(\fH\x00R\x06stdout\x12\x18\n" +
	"\x06stderr\x18\x02 \x01(\fH\x00R\x06stderr\x12\x1d\n" +
	"\texit_code\x18\x03 \x01(\x05H\x00R\bexitCodeB\n" +
	"\n" +
	"\bresponse\"\x91\x01\n" +
	"\x12CopyToGuestRequest\x12/\n" +
	"\x05start\x18\x01 \x01(\v2\x17.guest.CopyToGuestStartH\x00R\x05start\x12\x14\n" +
	"\x04data\x18\x02 \x01(\fH\x00R\x04data\x12)\n" +
	"\x03end\x18\x03 \x01(\v2\x15.guest.CopyToGuestEndH\x00R\x03endB\t\n" +
	"\arequest\"\x9f\x01\n" +
	"\x10CopyToGuestStart\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12\x12\n" +
	"\x04mode\x18\x02 \x01(\rR\x04mode\x12\x15\n" +
	"\x06is_dir\x18\x03 \x01(\bR\x05isDir\x12\x12\n" +
	"\x04size\x18\x04 \x01(\x03R\x04size\x12\x14\n" +
	"\x05mtime\x18\x05 \x01(\x03R\x05mtime\x12\x10\n" +
	"\x03uid\x18\x06 \x01(\rR\x03uid\x12\x10\n" +
	"\x03gid\x18\a \x01(\rR\x03gid\"\x10\n" +
	"\x0eCopyToGuestEnd\"j\n" +
	"\x13CopyToGuestResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\x12#\n" +
	"\rbytes_written\x18\x03 \x01(\x03R\fbytesWritten\"M\n" +
	"\x14CopyFromGuestRequest\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12!\n" +
	"\ffollow_links\x18\x02 \x01(\bR\vfollowLinks\"\xcf\x01\n" +
	"\x15CopyFromGuestResponse\x124\n" +
	"\x06header\x18\x01 \x01(\v2\x1a.guest.CopyFromGuestHeaderH\x00R\x06header\x12\x14\n" +
	"\x04data\x18\x02 \x01(\fH\x00R\x04data\x12+\n" +
	"\x03end\x18\x03 \x01(\v2\x17.guest.CopyFromGuestEndH\x00R\x03end\x121\n" +
	"\x05error\x18\x04 \x01(\v2\x19.guest.CopyFromGuestErrorH\x00R\x05errorB\n" +
	"\n" +
	"\bresponse\"\xe2\x01\n" +
	"\x13CopyFromGuestHeader\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12\x12\n" +
	"\x04mode\x18\x02 \x01(\rR\x04mode\x12\x15\n" +
	"\x06is_dir\x18\x03 \x01(\bR\x05isDir\x12\x1d\n" +
	"\n" +
	"is_symlink\x18\x04 \x01(\bR\tisSymlink\x12\x1f\n" +
	"\vlink_target\x18\x05 \x01(\tR\n" +
	"linkTarget\x12\x12\n" +
	"\x04size\x18\x06 \x01(\x03R\x04size\x12\x14\n" +
	"\x05mtime\x18\a \x01(\x03R\x05mtime\x12\x10\n" +
	"\x03uid\x18\b \x01(\rR\x03uid\x12\x10\n" +
	"\x03gid\x18\t \x01(\rR\x03gid\"(\n" +
	"\x10CopyFromGuestEnd\x12\x14\n" +
	"\x05final\x18\x01 \x01(\bR\x05final\"B\n" +
	"\x12CopyFromGuestError\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\x12\x12\n" +
	"\x04path\x18\x02 \x01(\tR\x04path\"H\n" +
	"\x0fStatPathRequest\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12!\n" +
	"\ffollow_links\x18\x02 \x01(\bR\vfollowLinks\"\xd8\x01\n" +
	"\x10StatPathResponse\x12\x16\n" +
	"\x06exists\x18\x01 \x01(\bR\x06exists\x12\x15\n" +
	"\x06is_dir\x18\x02 \x01(\bR\x05isDir\x12\x17\n" +
	"\ais_file\x18\x03 \x01(\bR\x06isFile\x12\x1d\n" +
	"\n" +
	"is_symlink\x18\x04 \x01(\bR\tisSymlink\x12\x1f\n" +
	"\vlink_target\x18\x05 \x01(\tR\n" +
	"linkTarget\x12\x12\n" +
	"\x04mode\x18\x06 \x01(\rR\x04mode\x12\x12\n" +
	"\x04size\x18\a \x01(\x03R\x04size\x12\x14\n" +
	"\x05error\x18\b \x01(\tR\x05error2\x96\x02\n" +
	"\fGuestService\x123\n" +
	"\x04Exec\x12\x12.guest.ExecRequest\x1a\x13.guest.ExecResponse(\x010\x01\x12F\n" +
	"\vCopyToGuest\x12\x19.guest.CopyToGuestRequest\x1a\x1a.guest.CopyToGuestResponse(\x01\x12L\n" +
	"\rCopyFromGuest\x12\x1b.guest.CopyFromGuestRequest\x1a\x1c.guest.CopyFromGuestResponse0\x01\x12;\n" +
	"\bStatPath\x12\x16.guest.StatPathRequest\x1a\x17.guest.StatPathResponseB'Z%github.com/onkernel/hypeman/lib/guestb\x06proto3"

var (
	file_lib_guest_guest_proto_rawDescOnce sync.Once
	file_lib_guest_guest_proto_rawDescData []byte
)

func file_lib_guest_guest_proto_rawDescGZIP() []byte {
	file_lib_guest_guest_proto_rawDescOnce.Do(func() {
		file_lib_guest_guest_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_lib_guest_guest_proto_rawDesc), len(file_lib_guest_guest_proto_rawDesc)))
	})
	return file_lib_guest_guest_proto_rawDescData
}

var file_lib_guest_guest_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_lib_guest_guest_proto_goTypes = []any{
	(*ExecRequest)(nil),           // 0: guest.ExecRequest
	(*ExecStart)(nil),             // 1: guest.ExecStart
	(*WindowSize)(nil),            // 2: guest.WindowSize
	(*ExecResponse)(nil),          // 3: guest.ExecResponse
	(*CopyToGuestRequest)(nil),    // 4: guest.CopyToGuestRequest
	(*CopyToGuestStart)(nil),      // 5: guest.CopyToGuestStart
	(*CopyToGuestEnd)(nil),        // 6: guest.CopyToGuestEnd
	(*CopyToGuestResponse)(nil),   // 7: guest.CopyToGuestResponse
	(*CopyFromGuestRequest)(nil),  // 8: guest.CopyFromGuestRequest
	(*CopyFromGuestResponse)(nil), // 9: guest.CopyFromGuestResponse
	(*CopyFromGuestHeader)(nil),   // 10: guest.CopyFromGuestHeader
	(*CopyFromGuestEnd)(nil),      // 11: guest.CopyFromGuestEnd
	(*CopyFromGuestError)(nil),    // 12: guest.CopyFromGuestError
	(*StatPathRequest)(nil),       // 13: guest.StatPathRequest
	(*StatPathResponse)(nil),      // 14: guest.StatPathResponse
	nil,                           // 15: guest.ExecStart.EnvEntry
}
var file_lib_guest_guest_proto_depIdxs = []int32{
	1,  // 0: guest.ExecRequest.start:type_name -> guest.ExecStart
	2,  // 1: guest.ExecRequest.resize:type_name -> guest.WindowSize
	15, // 2: guest.ExecStart.env:type_name -> guest.ExecStart.EnvEntry
	5,  // 3: guest.CopyToGuestRequest.start:type_name -> guest.CopyToGuestStart
	6,  // 4: guest.CopyToGuestRequest.end:type_name -> guest.CopyToGuestEnd
	10, // 5: guest.CopyFromGuestResponse.header:type_name -> guest.CopyFromGuestHeader
	11, // 6: guest.CopyFromGuestResponse.end:type_name -> guest.CopyFromGuestEnd
	12, // 7: guest.CopyFromGuestResponse.error:type_name -> guest.CopyFromGuestError
	0,  // 8: guest.GuestService.Exec:input_type -> guest.ExecRequest
	4,  // 9: guest.GuestService.CopyToGuest:input_type -> guest.CopyToGuestRequest
	8,  // 10: guest.GuestService.CopyFromGuest:input_type -> guest.CopyFromGuestRequest
	13, // 11: guest.GuestService.StatPath:input_type -> guest.StatPathRequest
	3,  // 12: guest.GuestService.Exec:output_type -> guest.ExecResponse
	7,  // 13: guest.GuestService.CopyToGuest:output_type -> guest.CopyToGuestResponse
	9,  // 14: guest.GuestService.CopyFromGuest:output_type -> guest.CopyFromGuestResponse
	14, // 15: guest.GuestService.StatPath:output_type -> guest.StatPathResponse
	12, // [12:16] is the sub-list for method output_type
	8,  // [8:12] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_lib_guest_guest_proto_init() }
func file_lib_guest_guest_proto_init() {
	if File_lib_guest_guest_proto != nil {
		return
	}
	file_lib_guest_guest_proto_msgTypes[0].OneofWrappers = []any{
		(*ExecRequest_Start)(nil),
		(*ExecRequest_Stdin)(nil),
		(*ExecRequest_Resize)(nil),
	}
	file_lib_guest_guest_proto_msgTypes[3].OneofWrappers = []any{
		(*ExecResponse_Stdout)(nil),
		(*ExecResponse_Stderr)(nil),
		(*ExecResponse_ExitCode)(nil),
	}
	file_lib_guest_guest_proto_msgTypes[4].OneofWrappers = []any{
		(*CopyToGuestRequest_Start)(nil),
		(*CopyToGuestRequest_Data)(nil),
		(*CopyToGuestRequest_End)(nil),
	}
	file_lib_guest_guest_proto_msgTypes[9].OneofWrappers = []any{
		(*CopyFromGuestResponse_Header)(nil),
		(*CopyFromGuestResponse_Data)(nil),
		(*CopyFromGuestResponse_End)(nil),
		(*CopyFromGuestResponse_Error)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_lib_guest_guest_proto_rawDesc), len(file_lib_guest_guest_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_lib_guest_guest_proto_goTypes,
		DependencyIndexes: file_lib_guest_guest_proto_depIdxs,
		MessageInfos:      file_lib_guest_guest_proto_msgTypes,
	}.Build()
	File_lib_guest_guest_proto = out.File
	file_lib_guest_guest_proto_goTypes = nil
	file_lib_guest_guest_proto_depIdxs = nil
}
