name: Release Hypeman API

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  release:
    runs-on: [self-hosted, linux, x64, kvm]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          # Not necessary to upload cache on self-hosted runner(s)
          # ~/go/pkg/mod and ~/.cache/go-build stay on disk between runs automatically.
          cache: false
          go-version: '1.25.4'

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v6
        with:
          # gorelease-pro is not required
          distribution: goreleaser
          version: '~> v2'
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
